- name: install and run nginx
  hosts: web
  become: yes
  tasks:

  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes


  - name: Create a directory if it does not exist
    ansible.builtin.file:
    path: /var/tmp/mallik
    state: directory
    mode: '0755'


